# Generated by Django 4.1.3 on 2024-03-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleapi', '0002_role_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='image',
            field=models.CharField(default='https://static.vecteezy.com/system/resources/previews/004/641/887/original/cartoon-carnival-tent-illustration-of-circus-tent-free-vector.jpg', max_length=200),
        ),
    ]
